create table if not exists public.quiz_resultados (
    id bigint generated by default as identity primary key,
    pontos integer not null check (pontos between 0 and 10),
    total_questoes integer not null default 10 check (total_questoes = 10),
    idioma text not null check (idioma in ('pt', 'en')),
    criado_em timestamptz not null default now()
);

alter table public.quiz_resultados enable row level security;

drop policy if exists "Permitir envio de resultados" on public.quiz_resultados;
create policy "Permitir envio de resultados"
on public.quiz_resultados
for insert
to anon, authenticated
with check (true);